### ISSUE TITLE
Error installing CoinGate

### ISSUE THREAD

**Issue by ghost** [coingate/whmcs-plugin#6]
<img width="1121" alt="Screen Shot 2022-07-29 at 12 54 47 AM" src="https://user-images.githubusercontent.com/68617474/181685496-5102ea5c-0562-49a1-8b93-0bf42e6ef337.png">

**Comment by linaspasv** [comment]
Hi @MaxieZ, make sure all files are copied and / or some are not missing on the server and make sure files got proper permissions based on your server configuration. :-)

**Comment by synuk** [comment]
We had same issue but you can check your error logs. Its most likely because when you download from GitHub they have path: modules/gateways/CoinGate 

But it should be without capitals so just rename the folder to "coingate" which I believe the release file on WHMCS marketplace link does correctly.

cc: @linaspasv

**Comment by linaspasv** [comment]
Oh, indeed. The old version had "CoinGate" library name, and 2.0.0 version using "coingate" but somehow GitHub did not respect the change.

**Comment by ghost** [comment]
> We had same issue but you can check your error logs. Its most likely because when you download from GitHub they have path: modules/gateways/CoinGate
> 
> But it should be without capitals so just rename the folder to "coingate" which I believe the release file on WHMCS marketplace link does correctly.
> 
> cc: @linaspasv

This fixed it. Thank you very much!
